### ISSUE TITLE
Dynamic Social Media Content Fetching

### ISSUE THREAD

**Issue by julientregoat** [prysmaticlabs/website#11]
A big focus for the next PR to the website will be fetching in external social media content - Medium, Twitter, Gitter, anything else you might want.

Since there are multiple ways we could do this, I had a couple of points of discussion in mind:

 - **What feeds should we be pulling in content in from and what should stay as a link?**
   - Medium appears to be most important
   - Twitter doesn't seem as important as the moment, maybe doesn't warrant a feed?
   - It could be cool to have a mini feed component for Gitter to show live updates and things happening in that manner.

- **Where to emphasize these feeds?**
  - Medium is our primary means of getting the big updates across. However, we also want to maintain the message being the first thing seen on page load. With the donors to be added to the bottom of the main page, I don't want to distract from any of those points. 
  - I'm thinking to create a 'Blog' or 'Feed' page that could aggregate these? Perhaps a small ticker or feed with our latest blog updates on the front page so it doesn't get lost in the mix? Or should we just add it to the front page? We could have a carousel type situation with the current `IntroContainer` as the first view, and perhaps a slow infinitely looping transition to a preview of the latest blog post update?
  -  A Gitter feed could be unintrusive on the first page if it was shown on hover over the button maybe? Alternatively, if a Blog / Feed page exists, it could live there

UPDATE:

Thinking noting our latest update somewhere on the front page, as a ticker type of situation perhaps, linking to a 'news' page that aggregates all of our feeds

**Comment by julientregoat** [comment]
@rauljordan thoughts?

**Comment by rauljordan** [comment]
I like the idea of some ticker or indicator when there is a new Medium update, and I could see us having a gitter/medium feed near the bottom of the page after the team section. Aside from that, I agree that the most important thing is for our mission/team to be the first thing users see. I'm happy with putting the updates at the bottom or on a different page, no real preference there.

**Comment by julientregoat** [comment]
Starting with this one and the realignment of the communicated vision

**Comment by rauljordan** [comment]
Closing
