### ISSUE TITLE
Embed MailChimp Mailing List Signup

### ISSUE THREAD

**Issue by julientregoat** [prysmaticlabs/website#12]
I didn't have this outlined in the timeline for PRs, but this seemed like something simple enough we could knock out if it was something that interested than you.

With MailChimp, we can embed in a subscribe link directly into the page. I'm not sure what settings that would require changing on the MailChimp side of things, but allowing the user to stay on the same page and continue browsing after a seamless sign up.

Thoughts?

**Comment by prestonvanloon** [comment]
This could be good as a dialog/modal. 
There shouldn't be any backend requirements, it's just a HTTP POST to mailchimp AFAIK.

Maybe this is a helpful module:
https://www.npmjs.com/package/react-mailchimp-subscribe
