### ISSUE TITLE
Change name of repo from `website` to `prysmatic-website` or other

### ISSUE THREAD

**Issue by sscheper** [prysmaticlabs/website#13]
When I view the Prysmatic website in the Github Desktop client (yes I'm a n00b that uses the desktop client), it loooks like this when viewed in the sidebar: 

<img width="225" alt="prysmatic-website-sidebar" src="https://user-images.githubusercontent.com/5298364/39526127-b468007e-4dd2-11e8-99d3-2c0865b8ecb0.png">

All contributors will just have to remember that `website` refers too Prysmatic's website. I can of course rename it locally; but I think any/all future contributors will have this issue, too. 

Not a big prio at all, but I'd recommend changing the name of this repo to either `prysmatic-website` or `prysmaticlabs.com`

**Comment by sscheper** [comment]
@prestonvanloon Yep it's always a pain to do this type of stuff; but probably better now then later (when people are working on a branch or something)

**Comment by prestonvanloon** [comment]
I think this would be better as a feature request to the GitHub client team. A typical pattern would be to clone the repository to a directory of whatever name you like.

git clone github.com/prysmaticlabs/website my-new-directory

If this functionality isn’t supported within the GitHub desktop client then maybe it should be added.

I’ll close this for now unless anyone feels really strongly about this or we continue to have feedback like this.

Thanks!
