### ISSUE TITLE
Align Site with Ethereum 2.0 Vision

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/website#17]
In addition to sharding, Prysmatic Labs will be tackling on ethereum 2.0 implementation. Let's reflect our new initiatives in our site. The new ethereum 2.0 implementation consists of casper (proof of stake) protocols, beacon chain processing, new cryptography schemes, additional actor roles. Here's some changes to make, feel free to add more.

- Change sharding to ethereum 2.0
- Don't mention go-ethereum project, we've already decoupled
- In addition to scaling throughput, talk about how we are securing and processing proof of stake chain

**Comment by julientregoat** [comment]
Going to get on this along with my other PRs starting next week! Sorry for the delay, been a hectic couple of months

**Comment by prestonvanloon** [comment]
Some of this was done in #21, but I think there is still room for improvement so I'll leave this open.
